# Generated by Django 2.0.5 on 2019-08-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='user',
            field=models.CharField(max_length=500),
        ),
    ]
